GET http://localhost:3001/players/

###

GET http://localhost:3001/players/5/

###

GET http://localhost:3001/matches/2/


###

PUT http://localhost:3001/players/7/
Content-Type: application/json

{
  "playerName": "Raju"
}

###

DELETE http://localhost:3001/players/

###

GET http://localhost:3001/players/3/matches

###

GET http://localhost:3001/matches/2/players

###

GET http://localhost:3001/players/1/playerScores